# Title: Water content impact on TOC 
Title: Impact of water content(moister) on TOC The real goal is amount of moister and TOC on plant growth and climent change.


Questions
* Relation between water content and TOC
* Does water content increse the level of TOC?
* How much water each soli type required to good for plant.
* The amount of TOC on each soil type

# Analysis All data

## Basics (Read, show columns and clean data)

In [235]:
import pandas as pd


df_main = df_main = pd.read_csv("LABORATORY_DATA.csv")
df_main

,PointID,County,Layer upper limit,Layer lower limit,Horizon lower limit,gS,mS,fS,gU,mU,...,Water content,Stone density,BD_bulk,Rock fragment fraction,Mn_Ox,Fe_Ox,Al_Ox,Mn_Di,Fe_Di,Al_Di
0,2,SH,0,10,28.0,5.8,33.4,35.4,13.1,3.2,...,20.21,2.65,1.17,2.072453,NaN,NaN,NaN,NaN,NaN,NaN
1,2,SH,10,30,28.0,6.7,32.0,35.8,13.3,3.2,...,19.58,2.65,1.43,2.307925,NaN,NaN,NaN,NaN,NaN,NaN
2,2,SH,30,50,54.0,5.0,27.9,37.8,17.5,3.5,...,15.74,2.65,1.47,2.803774,NaN,NaN,NaN,NaN,NaN,NaN
3,2,SH,50,70,68.0,7.6,31.4,36.6,14.4,3.0,...,11.75,2.65,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN
4,2,SH,70,100,96.0,5.8,43.1,42.3,4.1,1.3,...,5.93,2.65,1.59,3.928302,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17184,6211,NI,0,10,10.0,1.7,40.3,48.2,4.8,1.6,...,47.19,2.65,0.99,0.146415,NaN,NaN,NaN,NaN,NaN,NaN
17185,6211,NI,10,30,27.0,1.4,39.2,49.6,6.3,1.5,...,16.43,2.65,1.46,0.033208,NaN,NaN,NaN,NaN,NaN,NaN
17186,6211,NI,30,50,50.0,1.2,39.9,49.5,6.1,1.1,...,13.48,2.65,1.50,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
17187,6211,NI,50,70,70.0,1.2,40.9,53.5,2.7,0.5,...,11.84,2.65,1.63,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
17188,6211,NI,70,100,100.0,1.7,34.3,59.4,3.4,0.0,...,14.60,2.65,1.76,0.023396,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17189 entries, 0 to 17188
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PointID                 17189 non-null  int64
 1   County                  17189 non-null  object
 2   Layer upper limit       17189 non-null  int64
 3   Layer lower limit       17189 non-null  int64
 4   Horizon lower limit     17186 non-null  float64
 5   gS                      16708 non-null  float64
 6   mS                      16708 non-null  float64
 7   fS                      16708 non-null  float64
 8   gU                      16708 non-null  float64
 9   mU                      16708 non-null  float64
 10  fU                      16708 non-null  float64
 11  Sand                    16708 non-null  float64
 12  Silt                    16708 non-null  float64
 13  Clay                    16708 non-null  float64
 14  Soil texture class      17189 non-null  object
 15  pH_H2O                  17189 non-null  float64
 16  EC_H2O                  17189 non-null  float64
 17  pH_CaCl2                17189 non-null  float64
 18  TC                      17189 non-null  float64
 19  TOC                     17189 non-null  float64
 20  TIC                     17189 non-null  float64
 21  TN                      17185 non-null  float64
 22  TS                      2472 non-null   float64
 23  BD_FS                   17183 non-null  float64
 24  FSS                     17183 non-null  float64
 25  Water content           17134 non-null  float64
 26  Stone density           16870 non-null  float64
 27  BD_bulk                 13400 non-null  float64
 28  Rock fragment fraction  17171 non-null  float64
 29  Mn_Ox                   1737 non-null   float64
 30  Fe_Ox                   1737 non-null   float64
 31  Al_Ox                   1737 non-null   float64
 32  Mn_Di                   1319 non-null   float64
 33  Fe_Di                   1319 non-null   float64
 34  Al_Di                   1319 non-null   float64
dtypes: float64(30), int64(3), object(2)
memory usage: 4.6+ MB

In [50]:
df_main.describe()

,PointID,Layer upper limit,Layer lower limit,Horizon lower limit,gS,mS,fS,gU,mU,fU,...,Water content,Stone density,BD_bulk,Rock fragment fraction,Mn_Ox,Fe_Ox,Al_Ox,Mn_Di,Fe_Di,Al_Di
count,17189.000000,17189.000000,17189.000000,17186.000000,16708.000000,16708.000000,16708.000000,16708.000000,16708.000000,16708.000000,...,17134.000000,16870.000000,13400.000000,17171.000000,1737.000000,1737.000000,1737.000000,1319.000000,1319.000000,1319.000000
mean,2838.335156,34.744546,53.102682,66.328465,4.647486,18.060552,21.991124,18.904249,11.899395,5.606805,...,31.885268,2.648653,1.417255,6.416704,383.324041,3.773661,1.197686,475.271001,10.330978,1.573472
std,1801.174822,28.403525,34.035587,45.467435,6.467022,18.078286,19.617155,14.797635,8.558374,4.504407,...,82.445103,0.056129,0.302601,14.061328,688.360838,6.512071,1.010273,602.392587,8.961941,0.949273
min,2.000000,0.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.540000,1.000000,0.060000,0.000000,0.350000,0.010000,0.030000,-0.370000,0.040000,0.030000
25%,1263.000000,10.000000,30.000000,30.000000,0.700000,2.700000,5.775000,7.800000,4.200000,2.100000,...,12.572500,2.650000,1.320000,0.075472,51.020000,0.910000,0.550000,113.455000,3.420000,0.880000
50%,2728.000000,30.000000,50.000000,53.000000,2.400000,12.600000,16.200000,14.500000,10.800000,4.900000,...,18.790000,2.650000,1.480000,1.356981,212.160000,2.290000,0.990000,325.960000,8.960000,1.490000
75%,4390.000000,50.000000,70.000000,90.000000,5.600000,28.100000,33.600000,27.200000,19.000000,8.000000,...,24.830000,2.650000,1.600000,5.227882,528.250000,4.270000,1.510000,652.505000,14.640000,2.140000
max,6211.000000,169.000000,200.000000,201.000000,60.200000,95.900000,97.600000,80.600000,55.100000,44.600000,...,1431.590000,3.160000,2.090000,100.000000,16234.040000,129.470000,9.360000,10642.100000,110.980000,7.860000

In [253]:
# drop null values in `Water content` and `TOC` 
df_clean = df_main.dropna(subset=["Water content", "TOC", "BD_bulk"])

# exclue any negative `Water content`
df_clean = df_clean[df_clean["Water content"] > 0]

print(len(df_clean))

13398

## Add neccessary columns to using later, columns like `Soil type`, `Soil group`, `Layer group`
```
g/kg to %: Divide by 10 (since 10 g/kg = 1%)
% to g/kg: Multiply by 10
So the thresholds become:
For g/kg (your data):
Organic soils: TOC ≥ 300 g/kg (not 30!)
Mineral soils: TOC < 300 g/kg
```

In [254]:
import numpy as np


# Smaller than `ORGANIC_THRESHOD` consider as mineral soil type
ORGANIC_THRESHOLD = 120.0

df_extra = df_clean.copy()


# Add `Soil type` column which is eigter `Mineral` or `Organic`
df_extra["Soil type"] = np.where(df_clean["TOC"] >= ORGANIC_THRESHOLD, "Organic", "Mineral")

# Add `Soil group` which is either `Sand` `Silt` `Clay` or `Loam`
textures = {
    "sand": ("Ss", "Su2", "Sl2", "Sl3", "St2", "Su3", "Su4", "Slu", "Sl4", "St3", "fS", "fSms", "mS", "mSgs", "gS", "mSfs"),
    "clay": ("Ts4", "Ts3", "Tu3", "Tu4", "Ts2", "Tl", "Tu2", "Tt", "Ts3"),
    "silt": ("Uu", "Us", "Ut2", "Ut3", "Uls", "Ut4"),
    "loam": ("Ls2", "Ls3",  "Ls4",  "Lt2",  "Lts", "Lu", "Lt3"),
}

def get_soil_group(texture):
    texture = texture.strip()
     # Check each category
    if texture in textures["sand"]:
        return 'Sand'
    elif texture in textures["clay"]:
        return 'Clay'
    elif texture in textures["silt"]:
        return 'Silt'
    elif texture in textures["loam"]:
        return 'Loam'
    else:
        return 'Other'

# Make the `Soil group` column
df_extra['Soil group'] = df_extra['Soil texture class'].apply(get_soil_group)

# Add `Layer group` Which is either `Topsoil` for layer `0-30` or `Subsoil` for layer in range `30-100`
df_extra['Layer group'] = np.where(
    (df_clean['Layer upper limit'] >= 0) & (df_clean['Layer lower limit'] <= 30), 
    'Topsoil',
    'Subsoil'
)


df_mineral = df_extra[df_extra["Soil type"] == "Mineral"]
df_organic = df_extra[df_extra["Soil type"] == "Organic"]


df_mineral["Soil group"].value_counts()

Soil group
Sand     5951
Loam     2819
Silt     2281
Clay     1881
Other       1
Name: count, dtype: int64

## Mineral Soil Analysis

## Correlation

### Correlation Matrix
Looking at your correlation matrix:
    TOC vs Water content: 0.623 (moderate-strong positive)
    TOC vs Layer upper limit: -0.491 (moderate negative)
This means:
    TOC decreases with depth (negative correlation with layer upper limit)
    Water content increases with TOC (positive correlation)

In [255]:
df_mx = df_mineral[["TOC", "Water content", "TC", "pH_H2O", "Layer upper limit", "pH_CaCl2", "BD_bulk", "Layer lower limit", "Horizon lower limit", "TN"]]
correlation_matrix = df_mx.corr()
correlation_matrix

,TOC,Water content,TC,pH_H2O,Layer upper limit,pH_CaCl2,BD_bulk,Layer lower limit,Horizon lower limit,TN
TOC,1.000000,0.635152,0.850821,-0.159407,-0.516251,-0.110132,-0.767641,-0.522043,-0.465658,0.945303
Water content,0.635152,1.000000,0.583768,0.014718,-0.158691,0.047293,-0.683327,-0.164417,-0.151774,0.639993
TC,0.850821,0.583768,1.000000,0.094759,-0.388328,0.125374,-0.685675,-0.392946,-0.332804,0.809700
pH_H2O,-0.159407,0.014718,0.094759,1.000000,0.104293,0.979829,0.046697,0.107009,0.129730,-0.071368
Layer upper limit,-0.516251,-0.158691,-0.388328,0.104293,1.000000,0.051967,0.463203,0.983554,0.845878,-0.551163
pH_CaCl2,-0.110132,0.047293,0.125374,0.979829,0.051967,1.000000,0.004268,0.054833,0.080193,-0.016788
BD_bulk,-0.767641,-0.683327,-0.685675,0.046697,0.463203,0.004268,1.000000,0.475980,0.398626,-0.770215
Layer lower limit,-0.522043,-0.164417,-0.392946,0.107009,0.983554,0.054833,0.475980,1.000000,0.857845,-0.555967
Horizon lower limit,-0.465658,-0.151774,-0.332804,0.129730,0.845878,0.080193,0.398626,0.857845,1.000000,-0.490193
TN,0.945303,0.639993,0.809700,-0.071368,-0.551163,-0.016788,-0.770215,-0.555967,-0.490193,1.000000

### Correlation for each layer

In [256]:
from scipy.stats import pearsonr


def calculate_correlation_p(x, y):
    correlation, p_value = pearsonr(x, y)
    return round(correlation, 4), round(p_value, 4)


def determine_strength(correlation):
    # Determine strength and direction
    if abs(correlation) >= 0.7:
        strength = "strong"
    elif abs(correlation) >= 0.3:
        strength = "moderate"
    else:
        strength = "weak"
    return strength


def determine_direction(correlation):
    return "positive" if correlation > 0 else "negative"


def determine_significant(p_value):
    return p_value < 0.05


def create_correlation_table(data: dict[str, pd.DataFrame]):
    correlation_table =[] 
    for layer_name, df in data.items():
        x = df["Water content"]
        y = df["TOC"]
        corr, p = calculate_correlation_p(x, y)
        row = {
            "Layer group": layer_name,
            "correlation": corr,
            "p_value": p,
            "strength": determine_strength(corr),
            "direction": determine_direction(corr),
            "significant": determine_significant(p),
            "Mean TOC": round(df["TOC"].mean(), 1),
            "Mean Water c": round(df["Water content"].mean(), 1),
            "N samples": len(df),
        }
        correlation_table.append(row)
    df_correlation = pd.DataFrame(correlation_table)
    return df_correlation

# Mineral soil in different soil type.
df_mineral_group = {
    "0-30": df_mineral[df_mineral["Layer group"] == "Topsoil"], 
    "30-100": df_mineral[df_mineral["Layer group"] == "Subsoil"]
}
create_correlation_table(df_mineral_group)

,Layer group,correlation,p_value,strength,direction,significant,Mean TOC,Mean Water c,N samples
0,0-30,0.7240,0.0,strong,positive,True,20.4,23.1,5273
1,30-100,0.6219,0.0,moderate,positive,True,5.3,18.4,7660

### Correlation for each soil type

In [257]:
soils = {
    "Sand": df_mineral[df_mineral["Soil group"] == "Sand"],
    "Clay": df_mineral[df_mineral["Soil group"] == "Clay"],
    "Silt": df_mineral[df_mineral["Soil group"] == "Silt"],
    "Loam": df_mineral[df_mineral["Soil group"] == "Loam"],
}

dfs_correlation = []
for soil_name, soil_df in soils.items():
    layer_group = {
        "0-30": soil_df[soil_df["Layer group"] == "Topsoil"],
        "30-100": soil_df[soil_df["Layer group"] == "Subsoil"],
    }
    res_df = create_correlation_table(layer_group)
    # Add soil name to the res df
    res_df.insert(0, "Soil group", soil_name)
    dfs_correlation.append(res_df)

result = pd.concat(dfs_correlation, ignore_index=True)
result

,Soil group,Layer group,correlation,p_value,strength,direction,significant,Mean TOC,Mean Water c,N samples
0,Sand,0-30,0.7178,0.0,strong,positive,True,18.3,17.6,2397
1,Sand,30-100,0.6083,0.0,moderate,positive,True,4.8,13.5,3554
2,Clay,0-30,0.7469,0.0,strong,positive,True,28.0,32.5,644
3,Clay,30-100,0.7152,0.0,strong,positive,True,7.7,28.1,1237
4,Silt,0-30,0.6283,0.0,moderate,positive,True,15.5,23.7,1002
5,Silt,30-100,0.3541,0.0,moderate,positive,True,4.2,19.6,1279
6,Loam,0-30,0.7640,0.0,strong,positive,True,24.6,28.5,1230
7,Loam,30-100,0.6888,0.0,moderate,positive,True,5.6,21.0,1589

## Linear Regression

### For df_mineral no soil type or layer

In [260]:
import statsmodels.api as sm

# Define the independent variable (X) and dependent variable (y)
X = df_mineral[['Water content', "BD_bulk"]]  # Independent variable
y = df_mineral['TOC']            # Dependent variable

# Add a constant to the model (intercept)
X = sm.add_constant(X)

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    TOC   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.612
Method:                 Least Squares   F-statistic:                 1.021e+04
Date:                Sun, 28 Sep 2025   Prob (F-statistic):               0.00
Time:                        02:39:51   Log-Likelihood:                -46488.
No. Observations:               12933   AIC:                         9.298e+04
Df Residuals:                   12930   BIC:                         9.300e+04
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            66.4151      0.838     79.302      0.000      64.773      68.057
Water content     0.2237      0.008     27.662      0.000       0.208       0.240
BD_bulk         -40.8100      0.489    -83.440      0.000     -41.769     -39.851
==============================================================================
Omnibus:                     4756.640   Durbin-Watson:                   1.256
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            60460.148
Skew:                           1.405   Prob(JB):                         0.00
Kurtosis:                      13.213   Cond. No.                         303.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Soil type

In [274]:
import statsmodels.api as sm

# Define the independent variable (X) and dependent variable (y)
def print_ols(df, soil_name):
    X = df[['Water content', "BD_bulk"]]  # Independent variable
    y = df['TOC']            # Dependent variable
    
    # Add a constant to the model (intercept)
    X = sm.add_constant(X)
    
    # Fit the regression model
    model = sm.OLS(y, X).fit()

    print('-' * 20)
    print(soil_name)
    print('-' * 20)
    # Print the summary of the regression
    print(model.summary())


print_ols(soils["Sand"], "Sand")
print_ols(soils["Clay"], "Clay")
print_ols(soils["Silt"], "Silt")
print_ols(soils["Loam"], "Loam")

--------------------
Sand
--------------------
                            OLS Regression Results
==============================================================================
Dep. Variable:                    TOC   R-squared:                       0.628
Model:                            OLS   Adj. R-squared:                  0.628
Method:                 Least Squares   F-statistic:                     5024.
Date:                Sun, 28 Sep 2025   Prob (F-statistic):               0.00
Time:                        02:53:03   Log-Likelihood:                -20912.
No. Observations:                5951   AIC:                         4.183e+04
Df Residuals:                    5948   BIC:                         4.185e+04
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            66.3711      1.066     62.283      0.000      64.282      68.460
Water content     0.2753      0.011     26.166      0.000       0.255       0.296
BD_bulk         -39.8565      0.633    -62.916      0.000     -41.098     -38.615
==============================================================================
Omnibus:                     1721.124   Durbin-Watson:                   1.256
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            65117.670
Skew:                           0.688   Prob(JB):                         0.00
Kurtosis:                      19.147   Cond. No.                         230.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Clay
--------------------
                            OLS Regression Results
==============================================================================
Dep. Variable:                    TOC   R-squared:                       0.621
Model:                            OLS   Adj. R-squared:                  0.621
Method:                 Least Squares   F-statistic:                     1538.
Date:                Sun, 28 Sep 2025   Prob (F-statistic):               0.00
Time:                        02:53:03   Log-Likelihood:                -7134.9
No. Observations:                1881   AIC:                         1.428e+04
Df Residuals:                    1878   BIC:                         1.429e+04
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            85.3699      3.051     27.978      0.000      79.386      91.354
Water content     0.1171      0.028      4.240      0.000       0.063       0.171
BD_bulk         -54.7070      1.741    -31.424      0.000     -58.121     -51.293
==============================================================================
Omnibus:                      678.480   Durbin-Watson:                   1.556
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6487.864
Skew:                           1.415   Prob(JB):                         0.00
Kurtosis:                      11.647   Cond. No.                         465.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Silt
--------------------
                            OLS Regression Results
==============================================================================
Dep. Variable:                    TOC   R-squared:                       0.569
Model:                            OLS   Adj. R-squared:                  0.569
Method:                 Least Squares   F-statistic:                     1506.
Date:                Sun, 28 Sep 2025   Prob (F-statistic):               0.00
Time:                        02:53:03   Log-Likelihood:                -7098.8
No. Observations:                2281   AIC:                         1.420e+04
Df Residuals:                    2278   BIC:                         1.422e+04
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            44.3565      1.404     31.583      0.000      41.602      47.111
Water content     0.3586      0.018     20.117      0.000       0.324       0.394
BD_bulk         -30.0938      0.832    -36.168      0.000     -31.725     -28.462
==============================================================================
Omnibus:                      584.817   Durbin-Watson:                   1.432
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4479.963
Skew:                           0.996   Prob(JB):                         0.00
Kurtosis:                       9.570   Cond. No.                         322.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Loam
--------------------
                            OLS Regression Results
==============================================================================
Dep. Variable:                    TOC   R-squared:                       0.704
Model:                            OLS   Adj. R-squared:                  0.703
Method:                 Least Squares   F-statistic:                     3341.
Date:                Sun, 28 Sep 2025   Prob (F-statistic):               0.00
Time:                        02:53:03   Log-Likelihood:                -10146.
No. Observations:                2819   AIC:                         2.030e+04
Df Residuals:                    2816   BIC:                         2.031e+04
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            67.3689      1.951     34.534      0.000      63.544      71.194
Water content     0.3214      0.021     15.637      0.000       0.281       0.362
BD_bulk         -42.7047      1.071    -39.890      0.000     -44.804     -40.606
==============================================================================
Omnibus:                      861.709   Durbin-Watson:                   1.519
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8072.982
Skew:                           1.173   Prob(JB):                         0.00
Kurtosis:                      10.951   Cond. No.                         364.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Soil type and Layer

## Repeted

In [259]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import numpy as np

# Prepare data
X = df_clean_bdbluk[['Water content', "BD_bulk"]]  # Independent variable
y = df_clean_bdbluk['TOC']              # Dependent variable


# Create and fit model
model_all = LinearRegression()
model_all.fit(X, y)

p = 1 # number of predictors (features)
n = len(df_clean_bdbluk)
r2 = model_all.score(X, y)
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print(f"R-squared: {r2:.3f}")
print(f"Adjusted R-squared: {adj_r2:.3f}")
print(f"Number of samples: {n}")

R-squared: 0.612
Adjusted R-squared: 0.612
Number of samples: 12933

# Analysis for County

In [192]:
df_city = df_mineral[df_mineral['County'].str.strip().isin(['BB', 'BY', 'NI'])]  # BB, BY, NI
print("Number of samples:", len(df_city))
df_city["County"].value_counts()

Number of samples: 6793

County
BY            3005
NI            2577
BB            1211
Name: count, dtype: int64

### Correlation

In [208]:
# Mineral soil in different soil type.
df_city_group = {
    "0-30": df_city[df_city["Layer group"] == "Topsoil"], 
    "30-100": df_city[df_city["Layer group"] == "Subsoil"]
}
create_correlation_table(df_city_group)

,Layer group,correlation,p_value,strength,direction,significant,Mean TOC,Mean Water c,N samples
0,0-30,0.6835,0.0,moderate,positive,True,21.6,23.3,2584
1,30-100,0.6464,0.0,moderate,positive,True,5.6,18.7,4209

### Correlation for soil type in layer group

In [213]:
city_soils = {
    "Sand": df_city[df_city["Soil group"] == "Sand"],
    "Clay": df_city[df_city["Soil group"] == "Clay"],
    "Silt": df_city[df_city["Soil group"] == "Silt"],
    "Loam": df_city[df_city["Soil group"] == "Loam"],
}

dfs_city_correlation = []
for soil_name, soil_df in city_soils.items():
    city_layer_group = {
        "0-30": soil_df[soil_df["Layer group"] == "Topsoil"],
        "30-100": soil_df[soil_df["Layer group"] == "Subsoil"],
    }
    res_df_city = create_correlation_table(city_layer_group)
    
    # Add soil name to the res df
    res_df_city.insert(0, "Soil group", soil_name)
    dfs_city_correlation.append(res_df_city)

result_city = pd.concat(dfs_city_correlation, ignore_index=True)
result_city

,Soil group,Layer group,correlation,p_value,strength,direction,significant,Mean TOC,Mean Water c,N samples
0,Sand,0-30,0.6686,0.0,moderate,positive,True,18.9,17.3,1263
1,Sand,30-100,0.6132,0.0,moderate,positive,True,5.1,14.0,2263
2,Clay,0-30,0.6770,0.0,moderate,positive,True,27.3,32.7,287
3,Clay,30-100,0.7744,0.0,strong,positive,True,8.2,30.1,648
4,Silt,0-30,0.6577,0.0,moderate,positive,True,15.3,23.6,291
5,Silt,30-100,0.3085,0.0,moderate,positive,True,4.5,19.2,367
6,Loam,0-30,0.7245,0.0,strong,positive,True,26.1,29.5,741
7,Loam,30-100,0.7139,0.0,strong,positive,True,5.8,22.0,931